#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

set -x

${PREFIX}black djantic tests --check
${PREFIX}mypy djantic --disallow-untyped-defs --ignore-missing-imports
${PREFIX}flake8 djantic tests
