#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
    export PATH="venv/bin:$PATH"
fi

set -x

PYTHONPATH=. ${PREFIX}pytest --ignore venv --cov=djantic --cov-fail-under=100 --cov-report=term-missing "${@}"
