#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
    export PATH="venv/bin:$PATH"
fi

set -x

#mypy ./pydantic_django
PYTHONPATH=. ${PREFIX}pytest --ignore venv --cov=pydantic_django --cov-fail-under=100 --cov-report=term-missing "${@}"
black --check ./